# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GroupTransparency
                                 A QGIS plugin
 This plugin sets transparency for a layer group
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-27
        copyright            : (C) 2019 by Josef Källgården
        email                : groundwatergis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GroupTransparency class from file GroupTransparency.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .group_transparency import GroupTransparency
    return GroupTransparency(iface)
